### ISSUE TITLE
Results BO3 maps

### ISSUE THREAD

**Issue by SEBSOfficiel** [OhhLoz/HLTVBot#7]
Hello, on a match in BO3, the maps returned "Not Selected" and on / {team} maps, vertigo send undefined

**Comment by SEBSOfficiel** [comment]
@OhhLoz please can you fix it?

**Comment by OhhLoz** [comment]
Not Selected means that the api doesnt return a valid map, im not sure what you mean about the vertigo part

**Comment by SEBSOfficiel** [comment]
![image](https://user-images.githubusercontent.com/31318425/62301496-0afe6f00-b479-11e9-846c-27214062296d.png)

and can you fix the BO3 maps?

**Comment by OhhLoz** [comment]
I see thanks ill take a look, it should definitely be fixed soon in update 1.3.0. I plan to add pages too to reduce message spam. In the BO3 Not Selected is this is future matches to come (.matches/.livematches) or in results? Since for some events the maps arent selected until the match begins so I put the Not Selected for null values.

**Comment by OhhLoz** [comment]
Also, the undefined there is present in the HLTV api, so I can only assume they are maps that aren't in rotation/played professionally, I've already fixed it but will postpone pushing to the main bot until the pages are working.

https://i.imgur.com/YjNICg4.png

**Comment by SEBSOfficiel** [comment]
> Je vois que, grâce à la maladie, cela devrait être corrigé prochainement dans la mise à jour 1.3.0. Je prévois d'ajouter des pages aussi pour réduire le spam par message. Dans le BO3 non sélectionné, s'agit-il de correspondances futures à venir (.matches / .livematches) ou de résultats? Comme pour certains événements, les cartes ne sont pas sélectionnées jusqu'à ce que la correspondance commence, je mets donc Non sélectionné pour les valeurs nulles.

its for results

**Comment by OhhLoz** [comment]
Resolved in update v1.3.0
